apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: syspass-app-hpa 
    namespace: syspass
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: StatefulSet
      name: syspass-app-st 
    minReplicas: 1
    maxReplicas: 3
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 80
