---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: syspass-db-pvc
    namespace: syspass
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: syspass-config-pvc
    namespace: syspass
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: syspass-bkp-pvc
    namespace: syspass
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: syspass-session-pvc
    namespace: syspass
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
